# Generated by Django 5.0.3 on 2024-03-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_file',
        ),
        migrations.AddField(
            model_name='post',
            name='company',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
